### ISSUE TITLE
An error occures after pressing "Generate" button

### ISSUE THREAD

**Issue by DenkingOfficial** [dfaker/stable-diffusion-webui-cv2-external-masking-script#2]
OpenCV is installed, but it asks to rebuild the library

OS: Windows 10
Browser: Chrome

Log:

```
img2img:
Error completing request
Arguments: ('', '', 'None', 'None', None, {'image': <PIL.Image.Image image mode=RGBA size=384x640 at 0x218974A9700>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=384x640 at 0x218974C7A60>}, None, 0, 20, 0, 4, 0, False, False, 1, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, 512, 512, 0, 0, 64, False, 0, 3, False, '', '', 1024, False, '', '', 1, 50, 0, 4, 1, 512, 0.75, 0, 0.1, 0, 0.06, 1, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 4, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, None, '', False, False, 1, '', 4, '', True) {}
Traceback (most recent call last):
  File "C:\Software\Other Software\sdautomatic111\modules\ui.py", line 126, in f
    res = list(func(*args, **kwargs))
  File "C:\Software\Other Software\sdautomatic111\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Software\Other Software\sdautomatic111\modules\img2img.py", line 131, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\Software\Other Software\sdautomatic111\modules\scripts.py", line 140, in run
    processed = script.run(p, *script_args)
  File "C:\Software\Other Software\sdautomatic111\scripts\external_masking.py", line 141, in run
    p.image_mask,self.lastPolys  = display_mask_ui(p.init_images[0],p.image_mask,max_size,self.lastPolys)
  File "C:\Software\Other Software\sdautomatic111\scripts\external_masking.py", line 41, in display_mask_ui
    cv2.namedWindow('MaskingWindow', cv2.WINDOW_AUTOSIZE)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1250: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'
```

**Comment by dfaker** [comment]
Interesting, that seems to be a message you'd get from the headless version that doesn't have the GUI features included.

Do you want to try a:

`py -m pip uninstall opencv-python-headless -y`

To make sure it isn't there conflicting, and then:

`py -m pip install opencv-python --upgrade`

If that still fails it may also need:

`py -m pip install opencv-contrib-python` 

If that's the case apologies, I'll need to update the readme.
